// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-XfAUwc0i3wY0gwWu5APWaDcwS3eXVnQ',
    appId: '1:598026633058:web:5a6438ddadf2245aa8f63b',
    messagingSenderId: '598026633058',
    projectId: 'stock-control-pdm',
    authDomain: 'stock-control-pdm.firebaseapp.com',
    storageBucket: 'stock-control-pdm.appspot.com',
    measurementId: 'G-R31PW1BFZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7WFGRbaabjyhfe6B3475I6Swr78-xJvU',
    appId: '1:598026633058:android:ace378e117c4bc8ea8f63b',
    messagingSenderId: '598026633058',
    projectId: 'stock-control-pdm',
    storageBucket: 'stock-control-pdm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcP-zO9xmpkHCdentpddINiVp_096KyWY',
    appId: '1:598026633058:ios:e13b34a988df6677a8f63b',
    messagingSenderId: '598026633058',
    projectId: 'stock-control-pdm',
    storageBucket: 'stock-control-pdm.appspot.com',
    iosClientId:
        '598026633058-vahauug4mk44pahb8e2888mrqd0h5p6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockcontrol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcP-zO9xmpkHCdentpddINiVp_096KyWY',
    appId: '1:598026633058:ios:5b0eed0a9b56cacba8f63b',
    messagingSenderId: '598026633058',
    projectId: 'stock-control-pdm',
    storageBucket: 'stock-control-pdm.appspot.com',
    iosClientId:
        '598026633058-qdik77cmjc0o3hglnkubqtsh9eqdjvog.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockcontrol.RunnerTests',
  );
}
