#git.ignore
name: stock_control
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite:
  path: ^1.8.0

  cupertino_icons: ^1.0.2
  localization: ^2.1.0
  #flutter_svg_provider: ^1
  flutter_triple: ^1.2.7+4
  flutter_modular: ^5.0.3
  dio: ^5.1.0
  mailer: ^6.0.1
  firebase_auth_web: ^5.2.2
  firebase_auth: ^4.2.2
  firebase_database: ^10.2.3
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.12.0

flutter_native_splash:
  color: "#000000"
  image: "lib/assets/images/stock2.jpg"
  android: true

flutter_icons:
  image_path: "lib/assets/images/stock2_big.jpg"
  android: "launcher_icon"
  adaptive_icon_foreground: "lib/assets/images/stock2_back.png"
  adaptive_icon_background: "#000000"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/i18n/
    - lib/assets/images/
    - lib/assets/fonts/

  fonts:
    - family: Billabong
      fonts:
        - asset: lib/assets/fonts/Billabong.ttf
